docker/Dockerfile
docker/Dockerfile.dev
docker/Dockerfile.test
docker/Readme.md
docker/build.sh
docker/collect-deployment-artifacts.sh
docker/startkuksaval.sh

I began cleaning & making useful dockers
- A new "effcient" small docker that can be deployed and is prepared for multiarch builds using kuksa magic
- A more "sane", i.e. standard docker for quick testing/development based on stable ubuntu
For know I left Bojans test docker, as it includes some fancy stuff for compiling with clang etc., that still might be helpful for catching bugs
In both cases server starts, haven't spent so much time in setting up keys & stuff, still waiting for @tspreck updated docs/scripts...
@tspreck Please test, that you can at least build the amd64 "production" docker, everything esl is optional for now
@rohoet @daschubert  I am pretty sure there are no new dependencies... But I said that before, so please take a quick glance.... "New" docker build scripts are …

Multiarch production docker

---

docker/collect-deployment-artifacts.sh
src/Authenticator.cpp
src/main.cpp

This is a simple fix with no additonal dependenices
- fix jenkins: It wasn't able to create containers due to a script collecting the artifacts failing
- make sure the jwt.key is searched in the certificate directory and not in the cwd (otherwise it can not be easily configured in dockers
- Terminate if jwt key can not be loaded on startup (without a valid JWT key you can not do anything anyway)
tested by a colleague (who needed this fix) 
@daschubert  or @rohoet no dependencies, IMO can be merged directly

Fix docker container and jenkins build

---

docker/build.sh

Makes sure scripts returns with an error when docker build fails, so Jenkins notices and doesn't start archiving stale docker images

Return error code when docker build runs into problems

---

unit-test/config.ini

Disable MQTT feature in default config, as there are no MQTT unit tests at the moment and this file is also copied into the build folder. Starting kuksa.val server with MQTT enabled and no MQTT broker present, leads to unnecessary errors
Can be merged @rohoet  @daschubert

Disable MQTT in default/unit-test config

---

Jenkinsfile
README.md
docker/build.sh

Our "production" dockers did not have tags attached when "loading" them, because we saved them basing on SHA Hash (see here https://github.com/moby/moby/issues/3877 )  
This has been fixed.
Also the docu was missing to expose a port.
@wenwenchenbosch This fix couldn't possibly go wrong, but pls. check if it still builds/works for you 😄

Fix docker image tagging in  jenkins

---

vss-testclient/Pipfile
vss-testclient/Pipfile.lock
vss-testclient/testclient.py

add the following feature:
- autocompletion path for `getValue`, `setValue` and `getMetaData`
- autocompletion files only `.token` file
- colored json output
unfortunately, cmd2 does not support coloring input and autocompletion text. @SebastianSchildt & @nayakned : If you can some thing about it, pls let me know

add autocompletion and colored output

---

clients/feeder/dbc2val/dbcfeeder.py

For some reason the new super admin may be parsed with a new line at the end. In `dbcfeeder.py` this new line `\n` gets included in the authZ request. `jwt-cpp` then fails to decode the jwt.
The same issue does not occur in `vss-testclient/testclient.py`
This PR is a quick fix to strip any new line characters from the token when reading the token from file in `dbcfeeder.py`
Signed-off-by: Woerner Dominic (RBCH/PJ-IOT) <dominic.woerner2@ch.bosch.com>

remove possible newline from jwt in dbcfeeder.py

---

clients/common/clientComm.py
clients/vss-testclient/Dockerfile
clients/vss-testclient/README.md
clients/vss-testclient/builddocker.sh
clients/vss-testclient/requirements.txt

Dockerfile and helper script to containerize the vss-testclient.
We can later build it in CI (and push to dockerhub), so it is easier to get started playing with kuksa.val

Dockerized test client

---

src/VssDatabase.cpp
test/unit-test/RestV1ApiHandlerTests.cpp
test/unit-test/VssCommandProcessorTests.cpp
test/unit-test/VssDatabaseTests.cpp
test/unit-test/test_vss_rel_2.0.json
test/unit-test/w3cunittest.cpp

Base on the json key "datatype" respond the right value key type. This detected by some unit tests failure.
eg: w3cunittest.cpp: process_query_set_get_simple  the Vehicle.OBD.EngineSpeed data type is float as definition in test_vss_rel_2.0.json

Fix w3cunittest utests

---

Jenkinsfile
test/unit-test/VssCommandProcessorTests.cpp

This fixes two timestamp races in unittests (triggered more  easily due to the change to ms in #90 )
Also this fixes #96 and #93

Fix unittest timestamp races and Jenkinsfile

---

src/CMakeLists.txt

This should fix #101 
This PR makes sure max stack size are similar in glibc (e.g. Ubuntu) and MUSL (Alpine) builds, to get consistent results on both
Wrt the REST implementation: using a regex on non-length checked input is probably a bad idea, and generally you can probably still fuzz the whole thing to kingdome come.
I assume eventuall out experimental (pre-VISS2) REST prototype should be replaced with a better version anyway, so no cleanup for now. Should be good enough for experiments.
Also sidenote: This does _not_ increase memory usage, stack is reserved as virtual memory. The actual memory usage still depends on stack usage.

Set default stack size explicitely in build scripts

---

src/VssDatabase.cpp

As "promised"
Fixes/works around #107

Treat unknown datatypes in VSS as string

---

src/VssDatabase.cpp

Fixes #109 
I guess the whole type & bounds checking code can be iproved (and incorporate min/max), but for now I kept the coding pattern and just added `int64` und `unit64` to fix the problem that those data types could not be set

Support (u)int64 in set

---

README.md

Signed-off-by: Dennis Grewe <dennis.grewe@de.bosch.com>
added missing build-essential package as part of the pre-requisite installation steps for building kuksa.val in a new linux installation.

update missing pre-req for build-essential in README

---

run_tests.sh
test/unit-test/CMakeLists.txt

default `ctest` should show real results and result code. Only for jenkins, it is better to not return errer when some testcases failed, sothat jenkins can continue with generating test reports. Therefore add `TEST_RESULT_CODE` option for cmake

improve cmake ctest

---

src/VssDatabase.cpp

Should fix #133 
```json
Test Client> setValue Vehicle.OBD.DriveCycleStatus.MIL foo
{
"action": "set", 
"error": {
"message": "foo is not a bool. Valid values are true and false ", 
"number": 400, 
"reason": "Value passed is out of bounds"
}, 
"requestId": "9dfe6e60-3374-493a-aca8-30736a82d6f3", 
"timestamp": 1616169129422
}
Test Client> setValue Vehicle.OBD.DriveCycleStatus.MIL true
{
"action": "set", 
"requestId": "a10e1ee1-9732-4704-ad28-e9c614d00501", 
"timestamp": 1616169134986
}
Test Client> getValue Vehicle.OBD.DriveCycleStatus.MIL 
{
"action": "get", 
"path": "Vehicle.OBD.DriveCycleStatus.MIL", 
"requestId": "2d6d790f-8c48-40fb-bb30-a22f2da76e01", 
"timestamp": 1616169138448, 
"value": true
}
Test Client> 
```
I guess the whole typeCheck code is due for a refactoring when we tacke …

Correctly type check boolean values

---

kuksa_certificates/jwt/createToken.py
kuksa_certificates/jwt/requirements.txt

only a hotfix. After releasing of jwt 2.0, the createToken script does not work any more.

createToken only works with jwt version 1.7 now

---

boost.cmake
docker/Dockerfile
docker/Dockerfile.dev

Fixes #186 
Approve/merge if builds on Azure CI go through, Eclispe CI still has permissions problems

Update Boost download URL to to retirement of bintray download service

---

include/VssCommandProcessor.hpp
include/VssDatabase.hpp
include/interface/IVssDatabase.hpp
src/VssCommandProcessor.cpp
src/VssDatabase.cpp
test/unit-test/VssDatabaseTests.cpp

Will fix #166 
Upon loading of a VSS file `default` entries will be copied to values.
```
~/kuksa.val/build/src$ ./kuksa-val-server --vss vss_release_2.1.json kuksa.val server
Commit 2f3afd9-dirty from 2021-05-06T11:43:05+02:00
Read configs from config.ini
Update vss path to /home/sebastian/kuksa.val/build/src/vss_release_2.1.json
Update cert-path to /home/sebastian/kuksa.val/build/src/.
Log START
VERBOSE: Try reading JWT pub key from /home/sebastian/kuksa.val/build/src/./jwt.key.pub
VERBOSE: SubscribeThread: Started Subscription Thread!
VERBOSE: VssDatabase::VssDatabase : VSS tree initialized using JSON file = /home/sebastian/kuksa.val/build/src/vss_release_2.1.json
INFO: Setting default for Vehicle/Body/ChargingPort/Type to unknown
INFO: Setting default for …
```

Apply default values upon initial loading of VSS tree

---

include/VSSRequestJsonSchema.hpp
include/VSSRequestValidator.hpp
include/VssCommandProcessor.hpp
src/VSSRequestValidator.cpp
src/VssCommandProcessor.cpp
test/unit-test/CMakeLists.txt
test/unit-test/Gen2GetTests.cpp
test/unit-test/Gen2SetTests.cpp
test/unit-test/UpdateMetadataTest.cpp
test/unit-test/UpdateVSSTreeTest.cpp

Will fix #191, adding unit tests, and some cleanup in schema validation code (less duplication)
I also added two simple tests for updateMetadata (had none so far), which slightly increases line coverage in command processor

Better validation and unit tests  for updateVSSTree

---

kuksa_feeders/dbc2val/dbc2vssmapper.py
kuksa_feeders/dbc2val/dbcfeeder.py
kuksa_feeders/dbc2val/mapping.yml
kuksa_feeders/dbc2val/requirements.txt
kuksa_feeders/dbc2val/transforms/mapping.py
kuksa_feeders/dbc2val/transforms/math.py

- Adds the abilty to transform data (mapping or math formula) to dbc feeder, allowing more flexible mapping. See updated `mapping.yml` for examples
- Will print error messages from kuksa.val server
Should have made detecting #211 much easier @anntexx 
Sidenote: The feeder/kuksa_viss _client is immensely slow for me.  I think some blocking problem, but that is a topic for another ticket :)
Can't add you as a reviewer @anntexx , but if can test whether DBC feeder works at least as good for you as before, would be nice

Transfromations and better error logging for DBC feeder

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
README.md

Devcontainer setup, to be able to do development directly in a VSCode managed docker
(also fixed an internal link in Readme.md `#Using-kuksaval`   -> `#using-kuksaval`

Add VSCode devcontainer configuration

---

include/JsonResponses.hpp
include/VSSRequestJsonSchema.hpp
include/VSSRequestValidator.hpp
include/VssCommandProcessor.hpp
src/JsonResponses.cpp
src/SubscriptionHandler.cpp
src/VSSRequestValidator.cpp
src/VssCommandProcessor.cpp
src/VssCommandSet.cpp
src/VssCommandUnsubscribe.cpp
src/VssProcessSubscribe.cpp
test/unit-test/Gen2GetTests.cpp
test/unit-test/Gen2SetTests.cpp
test/unit-test/KuksavalUnitTest.cpp
test/unit-test/RestV1ApiHandlerTests.cpp
test/unit-test/UpdateMetadataTest.cpp
test/unit-test/UpdateVSSTreeTest.cpp
test/unit-test/VssCommandProcessorTests.cpp

Fixes nothing in #263 , but makes subscriptions a little more robust
- enforcing string type subscriptionIDs both directions
- fixes the occasional "Integer Overflow" on unsubscribe
- JSON schema checking for subscribe and unsubscribe requests
- as a result, overall more helpful error messages
@nayakned  please check if it, at the very least, does not make things worse :)

Subscriptions Fixes 1

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json

Support for poor Mac OS users.
The previous  devcontainer variant "focal" (or buster) , will never be supported as ARM64 container, thus forcing emulation on current Macs, while bullseye works on AMR64 as well as AMD64.
(see also https://github.com/microsoft/vscode-dev-containers/issues/558 )
Does not affect builds.
Can you confirm it works on amd64 @nayakned ?

Change devcontainer to bullseye to also support ARM64 development  machines

---

.github/workflows/kuksa_databroker_build.yml
.github/workflows/kuksa_databroker_release.yml

When a tag with the form `databroker-vXX.XX.XX` is pushed, this workflow will run and:
* Push a multiarch container of databroker to ghcr.
* Create a draft release with databroker binaries.

[databroker] Add release workflow

---

kuksa_go_client/kuksa_viss/api.go
kuksa_go_client/main.go

You can now get, set and subscribe attributes using the go client.
The APIs have been extended in a backwards compatible manner accordingly.
The main.go now calls the new APIs (for get and set attributes) as an example.

Added the feature to get/set attributes to the go client.

---

kuksa_databroker/README.md

Remove informational text that might be misinterpreted as legal

---

kuksa_viss_client/__main__.py

A temporary fix that breaks the parsing loop when it finds an invalid path component.
Should fix #296 for now.
In the long term we can should use JSONPath for the autocompletion.

Fix for autocomplete

---

Jenkinsfile

Because feeders moved over to https://github.com/eclipse/kuksa.val.feeders

Remove gps feeder build from jenkins

---

Jenkinsfile

Jenkins builds often fail due to limited diskspace.
The largest artifact (>>1GiB) is the Ubuntu-based dev image. We will not archive it anymore (it is used for unittests, but normally not needed after, as development is done via VSCode .devcontainer anyway

Do not archive test dev container image used for unit tests

---

doc/liveUpdateVSSTree.md
kuksa-val-server/test/unit-test/readme.md

The GENIVI organization has changed its name to COVESA.

Replace GENIVI references with COVESA references

---

kuksa_databroker/Dockerfile
kuksa_databroker/README.md

With this PR the databroker container will by default load the VSS 3.0 file
```
erik@debian3:~/kuksa.val$ docker run --rm -it  -p 55555:55555/tcp databroker
2022-08-23T08:45:05.334442Z  INFO databroker: Init logging from RUST_LOG (environment variable not found)
2022-08-23T08:45:05.334473Z  INFO databroker: Starting Kuksa Data Broker 0.17.0
2022-08-23T08:45:05.334480Z  INFO databroker: Populating metadata from file 'vss_release_3.0.json'
2022-08-23T08:45:05.339142Z  INFO databroker: Listening on 0.0.0.0:55555
2022-08-23T08:45:05.339172Z  INFO databroker::broker: Starting housekeeping task
^C2022-08-23T08:45:12.903682Z  INFO databroker: received SIGINT
2022-08-23T08:45:12.903722Z  INFO databroker::grpc_service: Shutting down
```

Add default VSS file to Dockerfile

---

.clang-format
proto/kuksa/val/v1/types.proto
proto/kuksa/val/v1/val.proto

Hi guys,
too many meetings... I did a first horrible copy&paste orgy with some of the discussed things.
At this point it likely doesn't even run trough protoc compiler, however I think such a "fake PR" makes discussion easier.
Please feel free at this point to just push changes to this branch (of something comes out of it in the end, we can squash).
Idea is to have basic get/set/subscribe
Some comments in file. Still open points
- Do we want the "Update" streaming also in base? It does seem useful for some feeders (even though can feeder is not using it atm)
- We still need to think how/if at all we want to unify some of the metadata things. kuksa.databroker and kuksa.val-server differ a little bit here: val-server can do "everything"; but basically because it does not care at all, it …

First scratch of unified base proto

---

proto/kuksa/val/v1/types.proto
proto/kuksa/val/v1/val.proto

1. #### Move metadata fields to `.metadata` in `Datapoint`.
This makes it more clear what `VIEW_METADATA` refers to and it makes it possible to have `FIELD_METADATA`.
2. #### Add `fields` in addition to `view` in `Get` & `Subscribe`
This makes it possible to subscribe to single fields. It's not really needed for `Get` but it seems consistent to add it to both.
Because of this I also removed for example `VIEW_UNIT` since it's now equally easy to add `FIELD_METADATA_UNIT` to `fields`. In general I think `view` is a good solution to having a default view and a convenient way to request multiple fields. But perhaps not for specifying individual fields.
4. #### Include which fields have changed in subscription replies.
In order for a client to tell which field has changed (e.g. if it …

GRPC proto cleanup

---

kuksa_databroker/databroker/src/main.rs
kuksa_databroker/databroker/src/vss.rs

An _incomplete_ attempt to fix #339 as the Rust is weak within me.
What it currently does: Parsing default from JSON (keeping it as an "untyped" serde JSON value at that point), and during registering checking whether a default exist, and calling a function to apply it.
The challenge is, now the apply_default function would need a lot of code to convert the datatypes to the correct datapoints. Question @argerus , would that even be the right way to go? And if so, is now the right time, or will the new GRPC implementation change the required functions and structs a lot anyway?

Can parse defaults, but does not yet apply them

---

kuksa_viss_client/Dockerfile
kuksa_viss_client/KuksaWsComm.py

SSH checks in Python 3.10 are stricter.
Using current version with Python 3.10 gives the following error:
`Disconnected!! Cannot create a client socket with a PROTOCOL_TLS_SERVER context (_ssl.c:801)`
This seems to be correct as [CLIENT_AUTH](https://docs.python.org/3/library/ssl.html#ssl.Purpose.CLIENT_AUTH) used today is intended for server side sockets.
Changing to default context (i.e. implictly Purpose.SERVER_AUTH)
Also ignoring hostname check as default certificate does not include correct hostname
`Disconnected!! [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: IP address mismatch, certificate is not valid for '127.0.0.1'. (_ssl.c:997)`
Updating Docker build to use Python 3.10

Update kuksa-viss-client to support Python 3.10

---

kuksa_viss_client/Dockerfile
kuksa_viss_client/setup.py

This is a minor improvement that could save some time for local builds of the kuksa-client docker container.
Without this change all content of current working directory is copied. That is typically not that much if starting on fresh clone, but if you have built e.g. databroker before you may copy a lot of unused data.
It has been verified that building and running containers works with this change.
COPY is typically preferred over DD, see https://docs.docker.com/develop/develop-images/dockerfile_best-practices/

Limit contents copied when building kuksa-client container

---

kuksa_viss_client/setup.cfg

Fixes the license classifier for Python, otherwise Pypi does not accept the Python package
Note: The used classifier DOES refer to the Apache 2.0 license even though the official string does omit "2.0".
See here for many examples for Apache 2.0 licensed python packages: https://pypi.org/search/?c=License+%3A%3A+OSI+Approved+%3A%3A+Apache+Software+License

Fix license classifier for Pypi

---

proto/kuksa/val/v1/types.proto

VIEW_VALUE does not exist any longer, assuming VIEW_CURRENT_VALUE is correct.

Fix proto comment

---

Cargo.lock
kuksa_databroker/databroker/Cargo.toml
kuksa_databroker/databroker/src/main.rs

MUSL allocator is really slow. jemalloc is faster.

Add jemalloc for musl builds

---

kuksa-client/pyproject.toml

setuptools-git-versioning has more reasonable defaults for version templates than the custom ones we defined.
This commit fixes issue #254.

kuksa_client: Use setuptools-git-versioning's default templates

---

Cargo.toml
kuksa_databroker/databroker-cli/src/main.rs
kuksa_databroker/databroker/src/grpc/kuksa_val_v1/conversions.rs

Rust 1.65 introduced some clippy warnings and a compiler error.
- Fix clippy warning.
- Use `while let Some(..)` instead of `loop` as suggested by @flxo
- Remove split-debuginfo

Fix clippy warning (and compiler error)

---

kuksa-client/kuksa_client/__main__.py

So far, one could only get/set multiple target values, not any values. This fixes issue #424.

kuksa-client: Support getting/setting multiple values from CLI

---

kuksa-client/docs/examples/async-grpc.md
kuksa-client/docs/examples/sync-grpc.md
kuksa-client/kuksa_client/cli_backend/grpc.py
kuksa-client/kuksa_client/grpc/__init__.py
kuksa-client/kuksa_client/grpc/aio.py
kuksa-client/tests/test_grpc.py

`grpc.aio.VSSClient.subscribe*()` now return async iterators and no longer accept callbacks.
This allows easier subscriptions as one can now directly iterate over asynchronous updates using an `async for` loop.
This also removes the need for having a function (callback) call for every update we get on our subscription.
This also allows a similar API to exist for the synchronous API i.e. `grpc.VSSClient.subscribe*()`.

kuksa-client: Simplify grpc subscribe*() and add synchronous implementations

---

kuksa-client/kuksa_client/__main__.py

Ctrl-D closes stdin which in turn makes cmdloop() return. do_quit() is not called in this case.
This meant that the client thread would still be lying around and the main thread would then wait forevever for its termination. Move the exit logic outside of do_quit() to make sure we stop the client thread no matter how we exited the command loop.

kuksa-client: Make Ctrl-D stop kuksa-client

---

.github/workflows/kuksa_databroker-cli_build.yml
kuksa_databroker/Dockerfile-cli

This is fixing the problem that we do not have a container for the rust cli.
It has some bonus fixes, that we might roll out to other actions components
- The CLI is shipped in a `FROM scratch` container. Small. 
- There is some magic in there, that does extract the binaries from the container and provides them as GH Action artifacts (including bom. That may not technically be neccessary but is how things "should be done"(tm) if we were to include it in a release.  
- In the GH Action summary page it will print the location of the temporary docker for testing (easier than scrolling through hundreds lines of code)

Container for rust CLI

---

README.md

Minor PR: Since everything is APACHE in kuksa.val for a while, there is no need to list license for individual components.
While at it, added a badge for databroker build, and moved databroker  up from the bottom of the list

Rework badges and reorder items in README

---

.github/workflows/check_push_rights.yml

Use non-deprecated way to set outputs, removed unused output

check_push rights depreaction fix 

---

.github/actions/copy-from-oci/action.yml
.github/actions/post-container-location/action.yml
.github/workflows/check_push_rights.yml
.github/workflows/kuksa_databroker-cli_build.yml
.github/workflows/kuksa_databroker_build.yml
kuksa_databroker/Dockerfile

This changes the databroker docker file to build a static build running in a `FROM scratch` container (uncompresed container size < 7 MiB)
It also adapted the workflow to databroker-cli standard:
- Posting locations of generated temporary images for easy testing in build summary
- Extracting generated binaries from generated docker images providing them as build artifacts
Refactored the docker workflow, so that reusable parts now are composite actions, and also applied them for databroker-cli build -> Less code
Not sure CI in this PR will build correctly before this is merged upstream, for successful builds see 
https://github.com/boschglobal/kuksa.val/actions/runs/3854761392
and
https://github.com/boschglobal/kuksa.val/actions/runs/3854761389

Databroker updated container and binary export

---

kuksa_databroker/Dockerfile

Added toplevel Cargo.toml to databroker build as suggested in #443 
Result on arm
```
cs2rng@RNG-C-001JT kuksa.val % docker images | grep -e before -e after
databroker                                                                       after                  aa8915c2ffc0   20 seconds ago   3.89MB
databroker                                                                       before                 dce7ed03c82b   10 minutes ago   6.3MB
```
Please check @argerus

Include top level Cargo.toml in databroker container build

---

.github/workflows/check_push_rights.yml

Fix quoting, otherwise in certain conditions generates syntactically invalid if statements in bash, see e.g.
(https://github.com/boschglobal/kuksa.val/actions/runs/3910675145)

Fix quoting in check_push_rights

---

kuksa_databroker/README.md
kuksa_databroker/databroker/src/main.rs

The "--metadata" option now accepts a comma-separated list of file paths. This is helpful when supporting custom datapoints in addition to the standard ones.
Also made sure that the port parameter value is in the valid port range.

Support reading metadata from more than one file

---

kuksa_databroker/databroker/Cargo.toml
kuksa_databroker/databroker/build.rs
kuksa_databroker/databroker/src/main.rs

Just pushing version to next intended release.
Let's postpone "magic" to set this to the next minor release

Align databroker cargo version to next release

---

Cargo.lock

Otherwise Cargo.lock is updated during build leading to -dirty working copy when vergen checks

Update Cargo package version for databroker in Cargo.lock

---

Cargo.lock
kuksa_databroker/databroker/Cargo.toml
kuksa_databroker/databroker/src/main.rs

Making jemalloc an optional feature

---

kuksa_databroker/createbom/bomutil/maplicensefile.py
kuksa_databroker/createbom/createbom.py
kuksa_databroker/databroker-cli/src/main.rs
kuksa_databroker/databroker-examples/examples/perf_setter.rs
kuksa_databroker/databroker-examples/examples/perf_subscriber.rs
kuksa_databroker/databroker/build.rs
kuksa_databroker/databroker/src/broker.rs
kuksa_databroker/databroker/src/grpc/kuksa_val_v1/val.rs
kuksa_databroker/databroker/src/grpc/sdv_databroker_v1/broker.rs
kuksa_databroker/databroker/src/main.rs
kuksa_databroker/databroker/src/query/compiler.rs
kuksa_databroker/databroker/src/query/executor.rs
kuksa_databroker/databroker/src/vss.rs

https://rust-lang.github.io/rust-clippy/master/#uninlined_format_args
This lint was promoted from "pedantic" in Rust 1.67.0.  It was subsequently demoted to "pedantic" again in 1.67.1, so one solution would be to just use another version for now.
https://github.com/rust-lang/rust/pull/107743
It does however seem likely that it will be reintroduced at some point, so applying the fix now.
https://github.com/rust-lang/rust-clippy/pull/10265
* Handle empty license field
* Instead of aborting on first issue, print all problematic licenses / crates
* Add a bit more structure

CI fixes / improvements

---

Cargo.lock
kuksa_databroker/README.md
kuksa_databroker/databroker-cli/Cargo.toml
kuksa_databroker/databroker-cli/src/client.rs
kuksa_databroker/databroker-cli/src/main.rs
kuksa_databroker/databroker/Cargo.toml
kuksa_databroker/databroker/src/auth/mod.rs
kuksa_databroker/databroker/src/auth/token_decoder.rs
kuksa_databroker/databroker/src/grpc/sdv_databroker_v1/conversions.rs
kuksa_databroker/databroker/src/grpc/server.rs
kuksa_databroker/databroker/src/main.rs
kuksa_databroker/proto/sdv/databroker/v1/types.proto

Adds support for access tokens to databroker-cli.
Included are a number of other improvements. Some necessary for adding this support, some not. E.g.
* Add support for command line arguments
* Add initial support for subcommands
* Start moving GRPC related parts into client.rs
* A number of small updates to the interface

Add support for access tokens to cli

---

README.md

The Gitter badge link was broken.
Also fixed badge graphics to shield.io (as gitter switched over to matrix, wasn't sure how long badges.gitter.im will remain stable)

Fix Gitter badge

---

kuksa-client/kuksa_client/cli_backend/grpc.py

Handling ValueError exception in the event of incorrect values. Should fix #498

Catch exception for the client when incorrect types supplied as value.

---

kuksa_databroker/databroker/src/broker.rs
kuksa_databroker/databroker/src/grpc/kuksa_val_v1/val.rs
kuksa_databroker/databroker/src/grpc/sdv_databroker_v1/broker.rs
kuksa_databroker/databroker/src/grpc/sdv_databroker_v1/collector.rs
kuksa_databroker/databroker/src/main.rs

This adds another validation step before one can feed/set a path.
E.g. If you want to allow only a few options for setting you can do something like:
Vehicle.Body.Windshield.Front.Wiping.Mode - only allows: "OFF", "SLOW", "MEDIUM", "FAST", "INTERVAL", "RAIN_SENSOR"
Databroker now checks if the value you specified is in this list (if it is specified)

Enable enforcement of allowed values

---

.github/workflows/kuksa_databroker-cli_build.yml
.github/workflows/kuksa_databroker_build.yml
Cargo.lock
Cargo.toml
kuksa_databroker/Dockerfile
kuksa_databroker/Dockerfile-cli
kuksa_databroker/databroker-cli/Cargo.toml
kuksa_databroker/databroker-cli/src/client.rs
kuksa_databroker/databroker-examples/Cargo.toml
kuksa_databroker/databroker-proto/Cargo.toml
kuksa_databroker/databroker-proto/build.rs
kuksa_databroker/databroker/Cargo.toml
kuksa_databroker/databroker/build.rs

Also defined several dependencies shared by multiple packages as workspace dependencies so that their versions can be managed in a single place.

Upgrade to tonic 0.8.x

---

kuksa-client/kuksa_client/__init__.py
kuksa-client/kuksa_client/__main__.py
kuksa-client/kuksa_client/cli_backend/grpc.py
kuksa-client/kuksa_client/cli_backend/ws.py
kuksa-client/kuksa_client/grpc/__init__.py
kuksa-client/kuksa_client/grpc/aio.py

Use kuksa-client as non context-manager

---

kuksa-client/kuksa_client/__init__.py
kuksa-client/kuksa_client/__main__.py
kuksa-client/kuksa_client/cli_backend/__init__.py
kuksa-client/kuksa_client/cli_backend/grpc.py
kuksa-client/kuksa_client/cli_backend/ws.py
kuksa-client/kuksa_client/grpc/__init__.py
kuksa-client/kuksa_client/grpc/aio.py

This PR will fix the issue that the KUKSA client fails due to unathenticted state at the beginning. Alternatively we could give a default token which has no rights but the right structure (possible? @argerus). But I think we are good with not ensuring startup connection. Maybe we can even drop the ensure startup connection? it just calls ```get_server_info``` to ensure databroker is there. But for now I think this is a quick little fix. An other alternative could be to give the ability to set a token while strating the client through command line.

KUKSA client fails because at startup it is unauthenticated

---

.github/actions/check-dash/action.yml
.github/actions/copy-from-oci/action.yml
.github/workflows/kuksa_databroker-cli_build.yml
.github/workflows/kuksa_databroker_build.yml
kuksa_databroker/createbom/createbom.py

Eclipse uses dash-licenses (https://github.com/eclipse/dash-licenses)  to vet license of dependencies.
This PR does two things to better integrate with Eclipse process with less manual work for our RUST components
- it adds support to createbom to generate the inout file required by dash. I chose to create it via out existing tooling, instead of using the cmdline tricks in the dash-documentaiton example, so we have a "single source of truth" wrt to dependencies (i.e. what goes into the bom in the containers, is the same thing checked against dash).  In both cases this relies on cargo to get hte information
- I added a composite action, that will take a Dash input file, run it, and archive the full report, as well as the stdout/stderr output form dash
- I integrated into databroker and …

Dash-license support in CI

---

.github/actions/spdx/README.md
.github/actions/spdx/action.yml
.github/actions/spdx/verify-spdx-headers
.github/workflows/check_license.yaml

This PR adds checks for SPDX identifiers in files added/modified.
Action could possibly be reused by other KUKSA.val repositories
This PR replaces #537

Check SPDX license

---

.github/actions/spdx/README.md
.github/actions/spdx/action.yml
.github/actions/spdx/verify-spdx-headers
.github/workflows/check_license.yaml

Make sure that defined licenses are forwarded as arguments.
Increase scope of what is considered as comments
(Do not only check one-line comments)
Make sure to support comma separated list of comments
Example output checking for Apache or MIT
```
Prepare all required actions
Run ./.github/actions/spdx
Run $GITHUB_ACTION_PATH//verify-spdx-headers
2 will be accepted!
Allowed license: Apache-2.0
Allowed license: MIT
OK: Apache-2.0       /home/runner/work/kuksa.val/kuksa.val/kuksa-val-server/src/main.cpp
NO SPDX /home/runner/work/kuksa.val/kuksa.val/kuksa-val-server/test/unit-test/KuksavalUnitTest.cpp
OK: Apache-2.0       /home/runner/work/kuksa.val/kuksa.val/kuksa-val-server/test/unit-test/VssDatabaseTests.cpp
OK: Apache-2.0       /home/runner/work/kuksa.val/kuksa.val/kuksa_databroker/integra …
```

Refactoring SPDX check

---

.github/actions/spdx/verify-spdx-headers
kuksa-val-server/protos/kuksa.proto
proto/kuksa/val/v1/types.proto
proto/kuksa/val/v1/val.proto

Making sure all Proto files are licensed with Apache-2.0 Adapting SPDX pattern to accept multi line comments when searching for SPDX identifiers

Adapting SPDX checks for Proto files

---

kuksa_databroker/integration_test/helper.py
kuksa_databroker/integration_test/test_databroker.py

This should fix #539 
It waits fir the GRPC channel to become ready when a Databroker helper object is created.
If Databroker is not available, it will time out, and test will fail "as usual".
You can test it manually, by running the tests, and then when they seem to "hang" start databroker.
Should make CI more stable

Wait for databroker availability in integration tests

---

kuksa-client/kuksa_client/__main__.py
kuksa-client/kuksa_client/cli_backend/grpc.py
kuksa-client/kuksa_client/grpc/__init__.py

Example: 
```
setValue  Vehicle.Cabin.SeatPosCount [1, 2, 3]
```
```
getValue Vehicle.Cabin.SeatPosCount
{
"path": "Vehicle.Cabin.SeatPosCount",
"value": {
"value": {
"values": [
"1",
"2",
"3"
]
},
"timestamp": "2023-05-04T08:01:32.326616+00:00"
}
}
```

Give kuksa-client ability to encode array values to set and get them

---

Cargo.lock
kuksa_databroker/databroker/Cargo.toml
kuksa_databroker/databroker/build.rs
kuksa_databroker/databroker/src/main.rs

To fix a security issue in libgit, vergen needed to be updated. I upgraded to 8, and updated dependencies

Upgrade to Vergen 8 and update dependencies

---

doc/protocol/README.md
doc/protocol/support.md
kuksa-client/kuksa/val/v1/README.md
kuksa-val-server/protos/README.md
kuksa_databroker/proto/kuksa/val/v1/README.md
kuksa_databroker/proto/sdv/databroker/v1/README.md
proto/kuksa/val/v1/README.md

Background:
We currently have 3 sets of Protobuf APIs,
but it is not that easy by looking in repo to know how they are intended to be used.

Add documentation for Proto files.

---

kuksa_databroker/databroker/src/grpc/kuksa_val_v1/val.rs

This closes https://github.com/eclipse/kuksa.val/issues/553
Since SubscribeResponse does not return a protobuf error, the current approach is to use a tonic error as the return ErrorCode. This means that the error code returned will not be 404, but rather the tonic error code. However, it might be necessary to modify the SubscribeResponse to include DataEntryError as well.

Fix wrong error code when subscribing to a non-existing path

---

kuksa-client/kuksa_client/__init__.py
kuksa-client/kuksa_client/cli_backend/grpc.py
kuksa-client/kuksa_client/cli_backend/ws.py
kuksa-client/kuksa_client/grpc/__init__.py
kuksa-client/kuksa_client/grpc/aio.py
kuksa-client/setup.py

I tried running mypy, pylint and flake8.
Nothing alarming found but many false positives,
so we are not mature to enable them in CI.
This addresses some low hanging fruits.

Fixing some linter issues

---

.github/workflows/kuksa-client.yml

Reasons:
-the file does not only concern docker
-dbc2val not involved

Change name of kuksa-client CI tests

---

.github/workflows/kuksa-go.yml
kuksa-client/README.md
kuksa-client/kuksa_client/__main__.py
kuksa-client/kuksa_client/grpc/__init__.py
kuksa-client/tests/test_datapoint.py
kuksa_go_client/client_test.go
kuksa_go_client/kuksa_client/grpc.go
kuksa_go_client/main.go

This is work in progress. Background is that code scanning showed that the current regexp may be inefficient for certain strings. To see if it could be simplified without causing side effects a number of test cases has been added, which also partially proves as documentation on how it is intended to work. A similar change is one for the go client.

Kuksa Python & Go client: Refactor array handling and add tests

---

.github/workflows/kuksa-client.yml
.github/workflows/kuksa_val_docker.yml

Use default lifetime (24 hours) instead of 1h/8h, to be able to use e.g. a image build last night the following morning. 
Fixes #598

Use default time (24h) for ttl images

---

kuksa-val-server/README.md
kuksa-val-server/boost.cmake
kuksa-val-server/src/OverlayLoader.cpp

Background reason:
Newer gcc versions give more warnings, and we treat warnings as errors. We build our Docker container using alpine:3.11, but if you try to build locally there is big risk that you have a newer gcc version and runs into problems. The problems can be fixed by changing include and upgrading Boost version, as newer Boost has added a cast to the line below:
```
/home/erik/kuksa.val/kuksa-val-server/build/_deps/boost-build/include/boost/thread/pthread/thread_data.hpp:61:19: error: comparison of integer expressions of different signedness: ‘std::size_t’ {aka ‘long unsigned int’} and ‘long int’ [-Werror=sign-compare]
61 |           if (size<PTHREAD_STACK_MIN) size=PTHREAD_STACK_MIN;
|                   ^
compilation terminated due to -Wfatal-errors.
cc1plus: all warnings being …
```

Upgrade Boost for KUKSA.val Server

---

kuksa-client/README.md
kuksa-client/setup.cfg

Fixes #599
An example on the result can be seen in pypi, see https://test.pypi.org/project/kuksa-client/0.4.0a6/

Update status and author for kuksa-client

---

.flake8
.github/workflows/pre-commit.yml
.pre-commit-config.yaml
README.md

This will introduce pre-commit checks for kuksa-val. We already have it for kuksa.val.feeders
What it will do:
- For most files check that there is a line-break at end-of-file
- For most files verify that you do not have trailing blanks
- For python verify that flake8 pass, checking for instance line lengths
Suggest approach is to have a pre-commit hook installed on your local machine, then the check will be performed before you commit and this check shall be guaranteed to pass. But you may work reactively as well and fix issues if build fails and upload a new version. It only checks files affected by the commit/PR, but it checks the whole file, so initially you may need to fix some old sins.
Caveat: There might be cases where we do not want files to be changed, I took some settings …

Add pre-commit checks

---

.github/workflows/kuksa_databroker_build.yml

Old action is not maintained and uses Node.js 12, so will give us problems sooner or later
See https://github.com/actions-rs/toolchain/issues/216

Replace actions-rs/install build action

---

.github/workflows/kuksa-client.yml
kuksa-client/Dockerfile
kuksa-client/pyproject.toml

The reason is that all docker builds on master previously got version v0.1.6 which gave odd behavior if downloading kuksa-client:master or even latest
**Current behavior**
If downloading `kuksa-client:master` and running it then it will report `Welcome to Kuksa Client version 0.1.6`
This also occurs if downloading [kuksa-client:latest](https://github.com/eclipse/kuksa.val/pkgs/container/kuksa.val%2Fkuksa-client/81633962?tag=latest)
**Expected behavior**
Either real tag or something that shows that it is not tagged.
With this PR in CI the version will be like:
`0.3.1.post84+git.3cba9d41`
i.e. 84 commits after v 0.3.1
I have not tested that it reports right version for tagged versions on official repository
**How to reproduce**
```
erik@debian3:~/kuksa.val/kuksa-client$ docker pull …
```

Change kuksa-client version handling

---

kuksa-client/README.md
kuksa-client/tests/test_datapoint.py
kuksa_go_client/kuksa_client/ws.go
kuksa_go_client/main.go

Go client cannot handle setting of array values towards KUKSA Server.
Even if we have touched array handling somewhat lately I do not think this is new. If we intend to deprecate KUKSA Server then I do no think it is worth the effort to fix it.
(But if we want to support both gRPC and VISS/websocket going forward we would need to start defining more in detail what we need to support in both frameworks. Potentially discourage/forbid use of "internal quotes" as it only complicates things?)
This work-around makes sense for v0.4.0

Array handling: Align documentation to Broker/Server subset plus Workaround for Go Client to Server handling

---

kuksa-val-server/test/stresstest/config.ini
kuksa-val-server/test/stresstest/stress.py
kuksa-val-server/test/stresstest/stressClient.py
kuksa-val-server/test/unit-test/SubscriptionHandlerTests.cpp

I did a half hearted attempt running the tests.
But in short, they are not well documented.
And they are not included in CI, so will likely fail again.
Not essential for v0.4.0, but can be merged without risk for regressions

Some test fixes

---

kuksa_go_client/protocInstall/protocInstall.go

See https://cwe.mitre.org/data/definitions/22.html
Theoretical risk in short:
- We download a malicious zip archive
- The zip archive contains items like "../../usr/bin/something"
- We might end up with installing unwanted files at wrong places
Tested that it does not affect normal install
This was detected when running Github code scanning in my own fork

Fix protoc install vulnerability

---

.github/actions/unit-test/Dockerfile
.github/actions/unit-test/run_tests.sh
.github/workflows/kuksa_val_unittest.yml
doc/KUKSA.val_server/build-docker.md
doc/KUKSA.val_server/liveUpdateVSSTree.md
kuksa-val-server/README.md
kuksa-val-server/docker/Dockerfile
kuksa-val-server/docker/Dockerfile.dev

This aligns unit-tests with other triggers and now it works. It also removes explicit install of gRPC and Boost. That is included from cmake so not needed. The old warning that it might be needed for "older" versions of cmake shall likely not be relevant any longer, at least not if we assume that Ubuntu 20 or newer is used. 
Still the build takes time. A possible remedy for CI could be to join both builds to the same so we do not need to install boost and gRPC twice.
Now also using 4 threads (`-j 4` in all builds)

Testing KUKSA Server Unittest

---

kuksa_databroker/databroker-cli/Cargo.toml
kuksa_databroker/databroker-cli/src/client.rs
kuksa_databroker/databroker-cli/src/main.rs
kuksa_databroker/databroker/Cargo.toml
kuksa_databroker/databroker/src/grpc/server.rs
kuksa_databroker/databroker/src/main.rs

the tonic feature "_tls_" is made optional.
Behavior:
`cargo build --no-default-features --features=no-tls` => builds databroker without tonic/tls or rust-tls dependencies
`cargo build or cargo build --features=tls` => build with tls features.
Dependencies can be verified by running and comparing
`cargo tree --features no-tls --no-default-features > feat.txt`
`cargo tree --features tls > feat_tls.txt`

make tls stuff optional

---

kuksa_databroker/databroker-cli/src/main.rs
kuksa_databroker/databroker/src/broker.rs

Add the ability to set a value as being not available (i.e. the initial state of a signal that is not set).

Support setting value "NotAvailable"

---

kuksa-client/kuksa_client/__main__.py

- Show subscription events in client instead of writing them to a file (and suggesting the user tails them manually).

[kuksa-client] Show subscription events in client.

---

kuksa_databroker/databroker/src/broker.rs
kuksa_databroker/databroker/src/grpc/sdv_databroker_v1/broker.rs

A wrapper function that made it easy to iterate through metadata was already available in the broker interface:
```rust
broker
.map_metadata(|metadata| proto::Metadata::from(metadata))
.await
```
This has been generalized to iterate over entries instead (i.e. not only metadata) as that will be useful when in the `kuksa.val.v1` interface for example:
```rust
broker
.map_entries(|entry| {
// Extract stuff from all entries (including metadata)
}).await
broker
.filter_map_entries(|entry| {
// Extract stuff from some entries (including metadata)
}).await
```

Add iterator access for entries

---

kuksa-client/kuksa_client/__main__.py

An update to the way autocompletion works in kuksa-client. Builds on top of the newly added support for `kuksa.val.v1` by @rafaeling.
- Instead of listing the complete path for all completions, list only the currently completable path components.
- Only use columnar completion style.
- Complete branches with a trailing '.' and leafs without.

Updated kuksa-client autocompletion

---

kuksa_databroker/databroker/src/broker.rs
kuksa_databroker/databroker/src/grpc/sdv_databroker_v1/broker.rs
kuksa_databroker/databroker/src/main.rs

Fix permissions bug inadvertently introduced when adding `iter_entries()`.
Summary:
Access control in databroker is implemented by the need to have a `DatabaseReadAccess` in order to read anything from the db. It's only possible to get a `DatabaseReadAccess` if you supply a set of permissions, that will then be kept as a reference in this struct.
```rust
pub struct DatabaseReadAccess<'a, 'b> {
db: &'a Database,
permissions: &'b Permissions,
}
```
Once you have that, you have access to the database only available through the following interface.
```rust
impl DatabaseReadAccess {
pub fn get_entry_by_id(&self, id: i32) -> Result<&Entry, ReadError>;
pub fn get_entry_by_path(&self, path: impl AsRef<str>) -> Result<&Entry, ReadError>;
pub fn get_entries_by_regex(&self, regex: regex::Regex) -> …
```

[databroker] Fix permissions bug.

---

doc/quickstart.md
kuksa-client/README.md
kuksa-client/kuksa_client/__main__.py

Will close #657 
This tries to simplify connecting to VSS servers using kuksa-client CLI.  It uses URIs now, exmaples of valid URIs
```
grpc://127.0.0.1:55555
grpcs://127.0.0.1:55555
ws://127.0.0.1:8090
wss://127.0.0.1:8090
```
Other changes
- Changed default (when no command line parameters are given) to connecting to databroker instead of val server
- Removed the "set/getServerAddress" commands within the CLI, instead use `connect <URI>
- Updated Readme
When checking this, please also double check whether all variants (TLS/noTLS databroker, val-server) still work.
This is a change in the CLI part only, so the API itself is unaffected

Better cmdline args specifying server in kuksa-client

---

kuksa-client/kuksa_client/__main__.py

Sometimes people - including me -  try to type `exit` instead of `quit` to exit kuksa-client.
This PR makes sure exit and quit are equivalent.

kuksa-client: exit is an alias for quit now

---

NOTICE.md
data/vss-core/README.md
doc/tls.md
kuksa-client/README.md
kuksa-val-server/README.md
kuksa_certificates/README.md
kuksa_certificates/jwt/README.md

Fixes #659
Also clarifies jwt token naming for server and need to specify servername for tls
How to check links is described as part of release process at https://github.com/eclipse/kuksa.val/wiki/Release-Process#checking-links, I just improved it a bit.

Documentation update

---

kuksa_certificates/jwt/createToken.py

output_filename is not defined in else branch. Most likely author wanted to use input_filename instead

createToken.py: Fix typo output_filename => input_filename

---

kuksa-client/kuksa_client/cli_backend/grpc.py
kuksa-client/kuksa_client/grpc/__init__.py
kuksa-client/kuksa_client/grpc/aio.py
kuksa-client/tests/test_grpc.py
kuksa_databroker/databroker/src/broker.rs
kuksa_databroker/databroker/src/grpc/kuksa_val_v1/val.rs

**New expected behaviour**
1. Client remains as it was, just pre-commit style was updated.
2. Databroker responses works as follow:
- ```getValue(path)```: return value or error if there is any.
- ```getValues(path1, path2, ... , n)``` return all path values if there are no errors, if there is/are any error/errors it would return no **partial values** and just its corresponding error for each error path.
- ```getValue(wildcard)```: return value or error if there is any but **no partial values**
- ```getValues(wildcard1, wildcard2, ... , n)``` return all wildcard values if there are no errors, if there is/are any error/errors it would return no **partial values of any wildcard** and just its corresponding error for each error wildcard.
- ```getValues(wildcard1, path2, ... , n)``` return …

Use entries iterator that handles permissions correctly

---

kuksa-client/docs/examples/async-grpc.md
kuksa-client/docs/examples/sync-grpc.md
kuksa-client/kuksa_client/grpc/__init__.py
kuksa-client/kuksa_client/grpc/aio.py
kuksa-client/tests/test_grpc.py

Fixes #667
With this change, if calling `authorize` before `connect` you get:
```
erik@debian3:~/kuksa.val/kuksa-client$ ./hej.py 
Traceback (most recent call last):
File "/home/erik/kuksa.val/kuksa-client/./hej.py", line 105, in <module>
client.authorize(token)
File "/home/erik/kuksa.val/kuksa-client/kuksa_client/grpc/__init__.py", line 678, in wrapper
raise Exception("Server not connected! Call connect() before using this command!")
Exception: Server not connected! Call connect() before using this command!
erik@debian3:~/kuksa.val/kuksa-client$ 
```
PR consist of two types of changes:
* Exception instead of info for both sync and async
* Alignment of connection check, previously connection was checked just for subset

Raise exception if not connected

---

.github/workflows/kuksa-client.yml
kuksa-client/Dockerfile

This fixes #682 
On  a high level
- switch to a glibc build
- this reduced build times as grpc wheels exist
- as a side effect the existing glibc wheels are already small
- using pyinstaller only ship the parts of python necessary to run the client, thus reducing size over using a python base image
This fixes the huge size of the arm image, while at the same time even reducing the amd64 image compared to master
Arm64 size now
```
ttl.sh/kuksa.val/kuksa-client-ff43b39d56fff605c6330c078dea4b383cade50f        latest                 e2dce0b872fd   About a minute ago   73.1MB
```

Simplify kuksa-client docker build and reducing resulting image size

---

kuksa_databroker/databroker/src/broker.rs
kuksa_databroker/databroker/src/glob.rs
kuksa_databroker/databroker/src/grpc/kuksa_val_v1/val.rs

Databroker now accepts any path composed of any character except : and whitespace, i.e.
```
- Vehicle._kuksa.databroker.GitVersion
- Vehicle.Do_you_not_like_smörgåstårta
- Vehicle.tschö_mit_ö
- Vehicle.東京_Москва_r#true
```

Support all valid vss paths

---

kuksa_databroker/databroker/src/broker.rs
kuksa_databroker/databroker/src/grpc/kuksa_val_v1/val.rs

Output after setting Vehicle.PowerOptimizeLevel and Vehicle.IsMoving signals:
```
Test Client> subscribeMultiple Vehicle.*
{
"subscriptionId": "f5c6544f-f93d-4ef8-9532-5f537eb5a179"
}
[
{
"entry": {
"path": "Vehicle.IsMoving",
"value": {
"value": false,
"timestamp": "2023-10-19T08:38:21.467527+00:00"
}
},
"fields": [
"VALUE"
]
}
]
[
{
"entry": {
"path": "Vehicle.PowerOptimizeLevel",
"value": {
"value": 5,
"timestamp": "2023-10-19T08:38:53.230746+00:00"
}
},
"fields": [
"VALUE"
]
}
]
```

Subscribe to wildcard

---

.github/workflows/kuksa_databroker_build.yml
Cargo.lock
doc/protocol/support.md
kuksa-client/kuksa_client/__main__.py
kuksa-client/kuksa_client/cli_backend/ws.py
kuksa_databroker/databroker-cli/src/main.rs
kuksa_databroker/databroker-proto/src/lib.rs
kuksa_databroker/databroker/Cargo.toml
kuksa_databroker/databroker/src/broker.rs
kuksa_databroker/databroker/src/grpc/kuksa_val_v1/conversions.rs
kuksa_databroker/databroker/src/grpc/sdv_databroker_v1/conversions.rs
kuksa_databroker/databroker/src/lib.rs
kuksa_databroker/databroker/src/main.rs
kuksa_databroker/databroker/src/permissions.rs
kuksa_databroker/databroker/src/types.rs
kuksa_databroker/databroker/src/viss/mod.rs
kuksa_databroker/databroker/src/viss/server.rs
kuksa_databroker/databroker/src/viss/v2/conversions.rs
kuksa_databroker/databroker/src/viss/v2/mod.rs
kuksa_databroker/databroker/src/viss/v2/server.rs
kuksa_databroker/databroker/src/viss/v2/types.rs
kuksa_databroker/databroker/src/vss.rs
kuksa_databroker/proto/sdv/databroker/v1/types.proto

Add VISSv2 interface to databroker.
Gated by feature flag `viss` (not built by default).
Supports:
- `get`, `set`, `subscribe` and `unsubscribe`
- Authorization (using same jwt scope format as the other interfaces)
Not implemented:
- Filters
- TLS

Add (optional) VISSv2 interface

---

kuksa-client/kuksa_client/__main__.py

To meet the discussed configuration policy here https://github.com/eclipse/kuksa.val/issues/589 this adds in a first step some environment variables for the cli arguments. Futhermore this should be a place to discuss the removal of default tokens. The default tokens were not used anymore because they got overwritten. This gets fixed with this PR. 
The question is do we want to keep default tokens as default usage in or do we just want to keep them in the container that they can manually be used.
@argerus @erikbosch @SebastianSchildt @rafaeling

Update configuration of python-cli to configuration policy

---

Cargo.lock
kuksa_databroker/databroker/Cargo.toml

This commit fixes two vulnerabilities. The only manual change is to update chrono dependency that has dropped time support, see
https://github.com/chronotope/chrono/releases/tag/v0.4.30
Then the rest is just results of `cargo update`

Upgrade chrono

---

.dockerignore
.github/workflows/kuksa_databroker_build.yml
kuksa_databroker/Dockerfile
kuksa_databroker/build-all-targets.sh
kuksa_databroker/databroker/Cross.toml
kuksa_databroker/integration_test/run.sh

This builds and pushes RISCV containers as well. One step further towards full #666 
I extended the integration test, so that all containers are tested (before only the one similar to the runner architecture)
As the riscv builds need to based on glibc for the moment, there was no easy way to adapt the general docker file, so I switched to building with cross and having the docker just "package" the binaries. On the plus side
- this enables to run on standard Github runners as well
- Does not need the hacky (ingenious?) copy-from-oci action anymore
Once this is in, I'd give the rust-cli the same treatment

Build and test RISCV

---

.github/workflows/kuksa_databroker-cli_build.yml
kuksa_databroker/Dockerfile
kuksa_databroker/Dockerfile-cli
kuksa_databroker/build-all-targets-cli.sh
kuksa_databroker/build-all-targets.sh

uses the same pattern as datbaroker to build CLI. As a result it als emits RISCV binaries (glibc ones due to limitations in the ecosystem currently)
Hint: On a linux system with qemu-user-static (or similar) package installed the system can run/test any of the ocntainers, e.g. 
docker run --rm -it --net=host --platform linux/riscv64 ttl.sh/kuksa.val/kuksa-databroker-cli-1924d6d3a814e19efd84ec1cd210dabc6fc6a387
Currently supported platforms are `linux/amd64` , `linux/arm64`, `linux/riscv64`

RISCV builds for databroker-cli

---

kuksa_databroker/databroker/src/main.rs
kuksa_databroker/databroker/src/vss.rs
kuksa_databroker/doc/user_guide.md

Work in progress.
Tries to let user determine change_type (continous/on_change) via VSS model as suggested in #652 
The behavior is as follows:
With a standard VSS all sensor and actuator signals are registered with ChangeType `continuous` (I feel, as VSS itself does not specify this, continuous is a more "safe" choice in terms of expectations. Everything that comes in via provider is forwarded to subscribers. But this is just a default.) 
Attributes are set to ChangeType `static` - if have no idea what implications that has in databroker, is this correct?
If a signal defines the extra proper x-kuksa-changetype being either `onchange`, `continuous` or `static` the ChangeType is set respectively. 
To test: Start databroker, start to kuksa-clients, subscribe e.g. `Vehicle.Speed` in one of …

Configure change-type from VSS JSON

---

kuksa_databroker/databroker/src/grpc/kuksa_val_v1/val.rs
kuksa_databroker/databroker/src/main.rs
kuksa_databroker/databroker/src/query/compiler.rs
kuksa_databroker/databroker/src/viss/v2/server.rs

Newer clippy does not seem to like `get(0)` but prefer `first()`
(clippy 0.1.75 complained, but not clippy 0.1.73)
This shall fix the failing build on master.

Fix new Clippy issues

---

.github/workflows/check_license.yml
.github/workflows/kuksa-go.yml
.github/workflows/kuksa_databroker-cli_build.yml
.github/workflows/kuksa_databroker_build.yml
.github/workflows/kuksa_val_docker.yml
.github/workflows/kuksa_val_unittest.yml
.github/workflows/pre-commit.yml

Node.js 16 actions are deprecated.
Please update the following actions to use Node.js 20: actions/checkout@v3, docker/metadata-action@v4, docker/login-action@v2, docker/build-push-action@v4. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

Update actions to avoid Node.js 16 actions

---

.github/workflows/kuksa_val_docker.yml

Recent builds on master using self-hosted failed (see https://github.com/eclipse/kuksa.val/actions/workflows/kuksa_val_docker.yml)
With this change it works - but it takes a lot longer time (building grpc, boost, and so on for arm64) - so alternative solutions are welcome. But better than failing builds

Remove self-hosted dependency for KUKSA Server

---

kuksa_apps/node-red/README.md
kuksa_databroker/databroker/src/broker.rs
kuksa_databroker/databroker/src/query/compiler.rs
kuksa_databroker/databroker/src/query/executor.rs
kuksa_databroker/databroker/src/query/expr.rs
kuksa_databroker/databroker/src/types.rs

Enhancing query engine by:
1. LAG - Lag is now available in query engine - Each datapoint now contains also previous (lag) value. If there is request to feed some datapoint all subrscibers executing query where is possible to check if previous value is different. Than after all subscribes are notified previous lag value becomes the current one.
2. Subquery - SELECT now can use subqueries (check **executor.rs** unit tests)
- WARNING it is working slightly different than standart SQL, where we can SELECT something from subquery where usually FROM keyword is used and than values are selected from subquery. Here if:
```
SELECT 
Vehicle.Speed as notSubquerySpeed,
(SELECT Vehicle.Speed WHERE Vehicle.Speed <> LAG(Vehicle.Speed))
```
We will get value if Vehicle.Speed is valid and there is not …

LAG functionality, Subqueries, Comparing with NotAvailable values

---

Cargo.lock
Cargo.toml
kuksa_databroker/databroker-cli/Cargo.toml
kuksa_databroker/databroker-proto/Cargo.toml
kuksa_databroker/databroker/Cargo.toml
kuksa_databroker/lib/common/Cargo.toml
kuksa_databroker/lib/kuksa/Cargo.toml
kuksa_databroker/lib/sdv/Cargo.toml

This upgrades RUST edition to 2021 and also explicitly enables the new dependency resolver
This is supported since RUST 1.56, and usually we are building with much newer versions anyway
https://blog.rust-lang.org/2021/05/11/edition-2021.html
https://doc.rust-lang.org/edition-guide/rust-2021/default-cargo-resolver.html
The "next" release will be the 2024 edition, so guess switching to 2021 is pretty sensible now
https://blog.rust-lang.org/2023/12/15/2024-Edition-CFP.html
Will close #328

Switch to 2021 edition of Rust

---

Cargo.lock
kuksa_databroker/databroker/Cargo.toml
kuksa_databroker/databroker/src/grpc/server.rs

Experimental support for systemd notify
From the discussion in chat 
This is not perfect yet, so lets discuss here what is needed for "good enough" level
1. It uses https://crates.io/crates/sd-notify crate. The way that crate is written I assume we do not even need to hide it behind a feature flag: On a non-systemd (maybe even non Linux) it does no harm, as it determines systemd availability by just checking existence of a file. On a a systemd system, even when starting manually on the commandline, a notify doesn't hurt, systemd will just ignore it (I assume that is probably how all notify-enabled dameons work)
2. _When_ to signal ready state: I put the code in the last reachable statement in main _before_ the GRPC socket is up. So strictly speaking there is still a race conditions. As at …

Systemd notify support

---

kuksa_databroker/lib/Cargo.lock
kuksa_databroker/lib/Cargo.toml

use the resolver = 2 in Cargo.toml since it is the default resolver for rust edition 2021. ```cargo update``` failed for lib crate.

Use resolver=2 in Cargo.toml

---

kuksa_apps/node-red/README.md
kuksa_apps/node-red/mqtt/package-lock.json
kuksa_apps/node-red/mqtt/package.json

Update due to a vulnerability
Also make it clear that it is deprecated.
We do not intend to migrate it.
Lock file updated by `npm i --package-lock-only`
Verification done: Checked that we could start NodeRed like below.

Update and deprecate node-red example

---

Cargo.lock
README.md
kuksa_databroker/README.md
kuksa_databroker/databroker-cli/Cargo.toml
kuksa_databroker/databroker-cli/src/main.rs
kuksa_databroker/databroker-proto/Cargo.toml
kuksa_databroker/databroker/Cargo.toml
kuksa_databroker/databroker/src/main.rs
kuksa_databroker/lib/Cargo.lock
kuksa_databroker/lib/common/Cargo.toml
kuksa_databroker/lib/kuksa/Cargo.toml
kuksa_databroker/lib/sdv/Cargo.toml

Intended workflow:
- Merge this one
- Then tag repo with 0.4.3
- Then trigger ghcr containers for 0.4.3
After that we may consider removing Databroker code from this repo
*Note: This one shall maybe not be merged until we have performed sufficient testing on new repo, so that we can*
*release 0.4.4 in new repo at about the same time*

Add deprecation/migration note to Databroker

---

Cargo.lock
kuksa_databroker/lib/Cargo.lock

Replaces #767 
Fix rustls vulnerability.
Updated by `cargo update`

Updating dependencies

---

kuksa_apps/node-red/mqtt/package-lock.json
kuksa_apps/node-red/mqtt/package.json

Actual code is deprecated, not tested at all, just did
`cd ~/kuksa.val/kuksa_apps/node-red/mqtt`
`npm audit fix`

Fixing vulnerabilities
