Jenkinsfile
docker/Dockerfile
docker/Dockerfile-Jenkins-Build-Env
docker/build.sh

This adds a Jenkinsfile for automated builds
No functionality/code is changed so it should be ok to merge @rohoet @daschubert

Add Jenkjinsfile for automated builds

---

README.md
doc/cmake.md
docker/collect-deployment-artifacts.sh
docker/startkuksaval.sh
examples/dbc2val/dbcfeeder.py
examples/dbc2val/websocketconnector.py

Small fixes and improvements from hackathon day.
Only readme and small fixes without adding new functionalities or dependencies
Please confirm and merge @rohoet  or @daschubert 
Thx!

Some fixes and Readme improvements

---

src/WebSockHttpFlexServer.cpp

Fixes #21 
@wenwenchenbosch:  Pls. review

Terminate if we can not open/bind our listening port

---

include/MQTTClient.hpp
include/SubscriptionHandler.hpp
include/VssDatabase.hpp
include/interface/IClient.hpp
src/MQTTClient.cpp
src/SubscriptionHandler.cpp
src/VssDatabase.cpp
src/main.cpp
unit-test/config.ini

add prefix for mqtt topic feature and do some cleanup

---

Jenkinsfile
docker/Dockerfile-Jenkins-Build-Env
docker/build.sh

Some fixes and simplifications to our docker build setup. Pls merge @rohoet

Simplify docker setup in Jenkins

---

src/VssCommandProcessor.cpp

add error message for getMetadata Response for non existing branches

---

Jenkinsfile

Fixes a bug, Jenkins did archive the amd64 docker as arm64 👎  😢 
Please merge @rohoet @daschubert

Archive correct ARM64 image

---

README.md

Fixes https://github.com/eclipse/kuksa.val/issues/60

Add checkout instructions to Readme

---

README.md
test/unit-test/AuthenticatorTests.cpp
test/unit-test/CMakeLists.txt
test/unit-test/RestV1ApiHandlerTests.cpp
test/unit-test/SubscriptionHandlerTests.cpp
test/unit-test/VssCommandProcessorTests.cpp
test/unit-test/VssDatabaseTests.cpp
test/unit-test/mock/IClientMock.hpp
test/unit-test/mock/IVssDatabaseMock.hpp
test/unit-test/w3cunittest.cpp

- Update README
- Fix unit test build failure
- Remove not use database mock in AuthenticatorTests.cpp
- Update include paths, link libs name in CMakeLists.txt
- Change the json result check in BOOST_TEST

Fix utest build

---

buildinfo.h.in

Signed-off-by: Junhyung Ki <kijoonh91@gmail.com>

two redundant lines are removed

---

src/CMakeLists.txt

Signed-off-by: Phong Tran <tranmanphong@gmail.com>

clang do not know -Werror=maybe-uninitialized

---

clients/common/clientComm.py
clients/vss-testclient/testclient.py

Signed-off-by: Chen Wenwen (CR/AME5) <Wenwen.Chen@de.bosch.com>

use uuid for request id and move all requests from test client to comm client

---

clients/common/clientComm.py
clients/vss-testclient/Pipfile
clients/vss-testclient/Pipfile.lock
clients/vss-testclient/requirements.txt

use short requestId in testclient, so that, output looks better

Use shortuuid

---

include/JsonResponses.hpp
run_tests.sh
src/JsonResponses.cpp
src/SubscriptionHandler.cpp
src/VssCommandGet.cpp
src/VssCommandProcessor.cpp
test/unit-test/Gen2GetTests.cpp
test/unit-test/SubscriptionHandlerTests.cpp
test/unit-test/VssCommandProcessorTests.cpp

timestamp from s to ms

---

README.md
config.ini
doc/usage.md
src/CMakeLists.txt
src/WebSockHttpFlexServer.cpp
src/main.cpp

mv config ini to toplevel

---

src/MQTTPublisher.cpp

fix default version in topic prefix

---

docker/startkuksaval.sh
src/MQTTPublisher.cpp

solve #128 
now i can also start docker images without giving config

128 fix start script in docker images

---

src/VssCommandSet.cpp

Tries fixing #124 
This still has two loops, because for setting more than one value in one call (to be implemented) the sematics is, that the set will only be executed, if all elements can be set. So two loops
__Loop 0__:
- Checking write auhtorization (accordig to token)
- Check if the path exists in the tree
- Check if it is a valid element for writing (i.e. sensor or actor)
The latter two conditions are tested seperately to give meaningful error messages
__Loop 1__:
- set everything
there is a lot of error handling still (because everything is double checked when really calling `setSignal`), but the expectation is the set goes through

Eliminate loop

---

kuksa_apps/node-red/README.md
kuksa_apps/node-red/docker-compose.yml

see review finding here: https://github.com/eclipse/kuksa.val/pull/146#discussion_r604761871

improve readme for node red examples

---

kuksa_feeders/gps2val/gpsd_feeder.py

solve #154 
Thanks the great support from gpsd, I find now the function to avoid blocking call.

using gpsd.waiting() to ask if any data there

---

kuksa_apps/dapr/pubsub/publisher.py
kuksa_apps/dapr/state_store/state_store.py

I just see an error while stopping dapr apps, because of api changed last time

use correct stop function now

---

src/VSSTypeSanitizer.cpp
test/unit-test/VSSTypeSanitizerTests.cpp

149 check enumerations

---

kuksa_viss_client/__main__.py

fix autocompletion error and the bug with less completed

---

src/VSSTypeSanitizer.cpp

improve error message for integer overflow

---

kuksa_feeders/dbc2val/Readme.md
kuksa_feeders/dbc2val/dbcfeeder.py
kuksa_feeders/dbc2val/dbcreader.py

cleanup so that dbcfeeder can also terminate cleanly

125 cleanup dbc feeder

---

test/stresstest/config.ini
test/stresstest/websocketconnector.py

fixed stress test #197

---

kuksa_viss_client/__init__.py

expand home dir for token file for kuksa viss client

---

src/CMakeLists.txt

add -Wnoerror=nonnull

---

kuksa_feeders/dbc2val/dbcfeeder.py
kuksa_viss_client/__init__.py
src/SubscriptionHandler.cpp

220 improve client performance

---

src/main.cpp

fix compile error and warning

---

src/VssDatabase.cpp
test/unit-test/VssDatabaseTests.cpp

Accept default only for attributes according to VSS spec

---

README.md
config.ini
data/vss-core/vss_release_2.2.json
doc/usage.md
docker/collect-deployment-artifacts.sh
src/CMakeLists.txt

Will fix #243 
Added VSS 2.2 and used it as default in config and Readme

Add vss release 2.2

---

README.md
kuksa_feeders/gps2val/readme.md

Add supported type in readme

---

README.md
doc/protocol/get.md
doc/protocol/set.md
include/VSSRequestJsonSchema.hpp
include/VssDatabase.hpp
kuksa_viss_client/README.md
kuksa_viss_client/__init__.py
src/VSSTypeSanitizer.cpp
test/unit-test/CMakeLists.txt
test/unit-test/Gen2SetTests.cpp
test/unit-test/VSSTypeSanitizerTests.cpp

close https://github.com/eclipse/kuksa.val/issues/40

Add array support

---

kuksa_go_client/README.md
kuksa_go_client/kuksa_viss/api.go
kuksa_go_client/kuksa_viss/commn.go
kuksa_go_client/main.go

- Implemented subscribe and unsubscribe APIs
- Tested along with kuksa.val server
- #263 Pending.

Feature complete web-socket version of the Kuksa golang client.

---

src/VssCommandUnsubscribe.cpp
test/unit-test/VssCommandProcessorTests.cpp

Catch the not UUID exception during unsubscribing.

---

kuksa_go_client/.gitignore
kuksa_go_client/kuksa_viss/api.go
kuksa_go_client/kuksa_viss/commn.go
kuksa_go_client/kuksa_viss/config.go
kuksa_go_client/main.go

-  Added .gitignore.
-  Changes from golang linter.
-  Fixed unreachable code.

Minor fixes/improvements to the golang client.

---

docker/startkuksaval.sh

Copy CA.pem to config if not available in the config at start-up.

---

README.md

Added the link to the Azure CI Server.

---

.github/workflows/kuksa_feeders_docker.yml
.github/workflows/kuksa_val_docker.yml
.github/workflows/kuksa_viss_client.yml
README.md

Update readme badges and fix ghcr login

BUild & badge fix

---

README.md

Signed-off-by: Sebastian Schildt <sebastian.schildt@de.bosch.com>

Fix license badge for feeders

---

README.md
kuksa_viss_client/KuksaGrpcComm.py
kuksa_viss_client/KuksaWsComm.py
kuksa_viss_client/LICENSE
kuksa_viss_client/__init__.py
kuksa_viss_client/__main__.py
kuksa_viss_client/_metadata.py
kuksa_viss_client/setup.cfg

Signed-off-by: Sebastian Schildt <sebastian.schildt@de.bosch.com>

Update license headers to Apache-2.0

---

README.md
kuksa_go_client/LICENSE
kuksa_go_client/kuksa_viss/api.go
kuksa_go_client/kuksa_viss/commn.go
kuksa_go_client/kuksa_viss/config.go
kuksa_go_client/main.go

Adding correct license headers to GO client

Update license for GO client

---

README.md

Fix link to kuksa.val feeders

---

kuksa_viss_client/README.md

Improve kuksa-client documentation

---

kuksa_viss_client/README.md

Fix typo in README

---

kuksa_databroker/databroker/src/broker.rs
kuksa_databroker/databroker/src/grpc/kuksa_val_v1/val.rs

- Subscription will yield an initial notification containing current values of everything subscribed to.
- Return error if subscription request contains no entries.

[databroker] Add initial notification on subscription

---

kuksa-val-server/README.md

fix broken link of system-architecture.md

---

kuksa_databroker/README.md

Document non-working default port on OS X

---

kuksa-client/README.md
kuksa-client/kuksa/val/kuksa.proto
kuksa-client/kuksa_client/cli_backend/grpc.py
kuksa-client/kuksa_client/cli_backend/ws.py
kuksa-client/kuksa_client/grpc.py
kuksa-client/kuksa_client/grpc/__init__.py
kuksa-client/kuksa_client/grpc/aio.py
kuksa-client/setup.py
kuksa-client/tests/test_grpc.py

This PR mostly adds what is needed for the DBC feeder to work:
- Synchronous gRPC client
- gRPC kwargs e.g. metadata required for DAPR ID

kuksa_client: Sync gRPC client + gRPC kwargs e.g metadata

---

kuksa-val-server/README.md

Add correct location of container images in kuksa.val server readme

---

kuksa_databroker/databroker/src/main.rs

Add SIGTERM handler to databroker

---

kuksa_apps/README.md
kuksa_apps/s3/config.ini
kuksa_apps/s3/pyarrow_mapping.py
kuksa_apps/s3/readme.md
kuksa_apps/s3/requirements.txt
kuksa_apps/s3/s3_uploader.py

To test this PR, make sure you `pip install -e ../../kuksa-client`.

kuksa_apps: Add support for databroker to S3 uploader

---

.github/workflows/kuksa-client.yml
.github/workflows/kuksa_val_docker.yml

Fix docker login for val-server and python client due to updated check-access-rights

Fix docker login for kuksa.val and kuksa client CI

---

README.md
doc/quickstart.md

I think we are missing some quickstart instructions. This ones tires that, leaving lots of details out, but using the hopefully most important features in a way that will run on 95% of all systems,
@erikbosch can you take look (maybe add commits to the branch directly if you want to change something)

Add Quickstart documentation

---

kuksa_databroker/Dockerfile

Signed-off-by: Sebastian Schildt <sebastian.schildt@de.bosch.com>

Fix version display in databroker builds

---

.gitmodules

Remove kuksa-feeders

---

Cargo.lock
kuksa_databroker/databroker/Cargo.toml
kuksa_databroker/databroker/src/main.rs
kuksa_databroker/databroker/src/types.rs
kuksa_databroker/databroker/src/vss.rs

Add support for parsing `min`, `max` & `allowed`.

Update VSS parser

---

Cargo.lock
kuksa_databroker/databroker-cli/Cargo.toml
kuksa_databroker/databroker-examples/Cargo.toml
kuksa_databroker/databroker-proto/Cargo.toml
kuksa_databroker/databroker/Cargo.toml

Update the Cargo.toml's and update Cargo.lock file

Update Cargo files

---

kuksa_databroker/DEPENDENCIES

Dependecies as created by dash for released artifacts

Add dependencies as recommended by Eclipse process

---

kuksa_databroker/databroker/src/broker.rs

Here you maybe can review the unwanted merge changes at least for the unit test changes. You can leave your thoughts here. (plus it fixes cargo fmt issues of CI)

Review PR for unit tests and refactoring of code

---

doc/quickstart.md

Add hints how to use Docker Desktop.
This came up in #489 , so let's preserve the knowledge

Describe Docker Desktop workarounds for Windows and Mac OS

---

kuksa-client/kuksa_client/cli_backend/grpc.py
kuksa-client/kuksa_client/grpc/__init__.py
kuksa-client/kuksa_client/grpc/aio.py
kuksa-client/tests/test_grpc.py

Implement authorization for kuksa python library and use it in the kuksa client. It includes a cli command too.

Support authorization in kuksa client/library

---

kuksa-client/kuksa_client/__init__.py
kuksa-client/kuksa_client/cli_backend/grpc.py
kuksa-client/kuksa_client/grpc/__init__.py
kuksa-client/kuksa_client/grpc/aio.py

Added type hints in implementation of kuksa client. If I'm not wrong the type hints already exist in python library. Would solve #493

type hints in Python API

---

doc/deployment.md

Fix link in deployment documentation

---

kuksa_databroker/databroker-cli/src/main.rs

Add array support for cli + 2 tests

---

kuksa_apps/node-red/README.md
kuksa_apps/node-red/docker-compose.yml
kuksa_apps/node-red/feeders.yml

I do not know if they are necessary/wanted @SebastianSchildt could you check if we want these?

Fixes to get node-red example running

---

kuksa_databroker/databroker/src/grpc/kuksa_val_v1/val.rs

Related issue: https://github.com/eclipse/kuksa.val/issues/490

Only actuactor target value can be set

---

kuksa-val-server/src/main.cpp

Let KUKSA.val Server listen to SIGTERM

---

kuksa-client/README.md
kuksa-client/docs/examples/threaded.md

Update threaded API doc

---

.github/workflows/kuksa_databroker-cli_build.yml
.github/workflows/kuksa_databroker_build.yml
kuksa_databroker/databroker-proto/Cargo.toml
kuksa_databroker/databroker-proto/build.rs

It closes this issue: https://github.com/eclipse/kuksa.val/issues/557

Pre-build protoc from source

---

.github/workflows/kuksa-go.yml
kuksa-client/kuksa_client/grpc/__init__.py
kuksa_go_client/README.md
kuksa_go_client/client_test.go
kuksa_go_client/kuksa_client/commn.go
kuksa_go_client/kuksa_client/grpc.go
kuksa_go_client/main.go
kuksa_go_client/protocInstall/protocInstall.go

Two vulnerabilities detected if you run code scanning.
Formatting change introduced by "go fmt"
Trying to add an action to enforce formatting
For more format info see https://go.dev/doc/effective_go#formatting

Fix vulnerabilities and add go linter

---

README.md

Nothing critical for v0.4, but I think the main README could benefit from some updates, like not stating gRPC and KUKSA Server in the same sentence

Updating main readme

---

kuksa-client/requirements.txt
kuksa-client/setup.cfg
kuksa-client/test-requirements.txt

Triggering reason is a vulnerability in pygments<2.15 All *.txt files updated with pip-compile --upgrade

Update KUKSA-Client dependencies

---

kuksa_databroker/databroker/src/viss/v2/server.rs

Internal subscribe function signature was modified and not all call sites got updated.

[databroker] Update calls to subscribe

---

Cargo.lock
kuksa_databroker/databroker-cli/Cargo.toml
kuksa_databroker/databroker-examples/Cargo.toml
kuksa_databroker/databroker-proto/Cargo.toml
kuksa_databroker/databroker/Cargo.toml
kuksa_go_client/.gitignore
kuksa_go_client/README.md
kuksa_go_client/go.mod
kuksa_go_client/go.sum

For this PR I suggest to merge with a merge commit

Merge V0.4.1 back to master

---

Cargo.lock
kuksa_databroker/databroker/Cargo.toml
kuksa_databroker/databroker/tests/current_values.rs
kuksa_databroker/databroker/tests/world/mod.rs

Also adapted integration tests accordingly.

Update to Cucumber 20.0

---

kuksa_databroker/databroker-examples/Cargo.toml

Author for other Cargo entities was made as part of the release, but this file was missed

Change author for Databroker-examples

---

.pre-commit-config.yaml
kuksa-client/kuksa_client/__main__.py

kuksa-client move: Add notice about new location to get updated version

---

README.md
doc/server-vs-broker.md
kuksa-val-server/README.md
kuksa-val-server/src/main.cpp

Deprecate KUKSA Server

---

.github/actions/copy-from-oci/action.yml
.github/workflows/kuksa_databroker-cli_build.yml
.github/workflows/kuksa_databroker_build.yml
.github/workflows/kuksa_val_docker.yml
.github/workflows/kuksa_val_unittest.yml

See https://github.com/eclipse/kuksa.val/issues/752
Also fixing some NodeJS warnings

Fix unknown/unknown docker images

---

kuksa_databroker/doc/QUERY.md

Updated markdown table header to properly render in preview

Fixed query table header in docs

---

kuksa_apps/node-red/mqtt/package-lock.json
kuksa_apps/node-red/mqtt/package.json

No tests performed, as the repo not yet has reached end of life we do minimal maintenance to upgrade vulnerabilities.

Updating dependencies to fix vulnerability
